### ISSUE TITLE
Disabling swap - "swap_file_state: absent" doesn't survive a reboot

### ISSUE THREAD

**Issue by RossLYoung** [geerlingguy/ansible-role-swap#19]
Using Ubuntu 20.04
The role works initially but after a reboot, swap is reported in /proc/meminfo

To make it persist, instead of changing the values in /etc/fstab to 0, comment/delete the swap line.

**Comment by ptr-dorjin** [comment]
It doesn't survive reboot on Raspberry Pi OS Buster, as well.
This solution worked: https://raspberrypi.stackexchange.com/a/100606/131018
```
sudo dphys-swapfile swapoff
sudo dphys-swapfile uninstall
sudo update-rc.d dphys-swapfile remove
sudo apt purge dphys-swapfile
```

I'd be glad to add the fix to this role but I'm not sure how to do it in Ansible for all different OS types without breaking anything.
