### ISSUE TITLE
The disable turns off ALL swap entries, not just this one

### ISSUE THREAD

**Issue by l8gravely** [geerlingguy/ansible-role-swap#27]
Looking at the disable.yml task, it calls the 'swapoff -a' command, which is wrong because it will remove all swap entries, not just the one  the role is interested in.  If you have multiple swap file entries, this will cause wierd problems.

I don't have a test case, but when I get a chance I'll try to whip one up to show the issue.   But from what I can see, this role just assumes one swap file to be added, but disables all swap entries (device or file) when you disable.

**Comment by P-N-L** [comment]
I ran into this problem recently, it was very confusing and counter-intuitive!
