### ISSUE TITLE
Support setting priority

### ISSUE THREAD

**Issue by esolitos** [geerlingguy/ansible-role-swap#6]
On a system there can be multiple swap files/partitions, setting a priority allows to use the fast swap first and only later more slow swap destinations.

This is also useful if one wants to replace the current swap file in a graceful way:
- Run the playbook to create (and use) the new swap file and set high priority.
- Wait a while (depends on the system usage) so that the new swap file is being used
- Run the playbook to disable and remove the old swap file.

Doing it in this way avoids spikes in resource usages.

**Comment by kmonticolo** [comment]
@esolitos https://galaxy.ansible.com/kmonticolo/ansible-role-swap
