### ISSUE TITLE
make creating swapfile faster

### ISSUE THREAD

**Issue by tpo** [geerlingguy/ansible-role-swap#9]
I suggest to use fallocate instead of dd, as proposed here: https://stackoverflow.com/a/33071279

**Comment by colin-nolan** [comment]
The use of fallocate - via the `swap_file_create_command` variable - is discussed in the README.

**Comment by tpo** [comment]
> This issue has been marked 'stale' due to lack of recent activity. If there is no further activity, the issue will be closed in another 30 days. Thank you for your contribution!

Thanks @stale bot for reminding me that I need to do something about my ticket :-)

**Comment by tpo** [comment]
This ticket can be closed in favour of #13
